// C:\Users\darin\Documents\UNACH\UNACH\src\components\organism\Section1_2Data.jsx

export const AC = () => {
    return `Facultad de Contaduría y Administración-C-I,
  Facultad de Ciencias de la Administración-C-IV,
  Facultad de Negocios-C-lV,
  Facultad de Ciencias Administrativas-Comitán C-VIII,
  Facultad de Contaduría y Administrativas-Pichucalco-C-Vll,
  Escuela de Ciencias Administrativas-C-IX-Arriaga,
  Escuela de Ciencias Administrativas-Isthmo-Costa-C-lX-Tonalá,
  Centro Universidad-Empresa,
  Facultad de Ciencias Sociales-C-III,
  Facultad de Humanidades-C-Vl,
  Escuela de Humanidades-C-IV-Tapachula,
  Escuela de Humanidades-C-IX-Pijijiapan,
  Facultad de Arquitectura-C-I,
  Facultad de Ingeniería-C-I,
  Facultad de Lenguas-Tuxtla,
  Escuela de Lenguas-San Cristóbal,
  Escuela de Lenguas-Tapachula,
  Facultad de Medicina Humana-C-II-Dr. Manuel Velasco Suárez,
  Facultad de Ciencias Químicas-C-IV,
  Facultad de Medicina Humana-C-IV-Tapachula,
  Escuela de Ciencias Químicas-Ocozocoautla,
  Centro Mesoamericano de Estudios en Salud Pública y Desastres-CEMESAD,
  Facultad de Medicina Veterinaria y Zootecnia-C-II,
  Extensión de la Licenciatura en Medicina Veterinaria Y Zootecnia-Pichucalco,
  Facultad de Ciencias Agrícolas-C-IV,
  Facultad de Ciencias Agronómicos-C-V,
  Facultad Maya de Estudios Agropecuarios,
  Escuela de Ciencias y Procesos Agropecuarios Industriales-Istmo-Costa C-IX-Arriaga,
  Escuela de Estudios Agropecuarios Mezcalapa,
  Centro de Estudios Etnogropecuarios-C-lll-San Cristóbal,
  Escuela de Estudios Agropecuarios Mezcalapa,
  Centro de Estudios Etnoagropecuarios-C-III-San Cristóbal,
  Coordinación de la Licenciatura en Caficultura,
  Coordinación de licenciatura en sistemas Costeros,
  Facultad de Ciencias en Física y Matemáticas,
  Instituto de Biociencias,
  Centro Mesoamericano de Física Teórica,
  Facultad de Derecho-C-III,
  Instituto de Investigaciones Jurídicas,
  Centro de Estudios para el Desarrollo Municipal y Políticas Públicas-CEDES,
  Centro de Estudios para la export Construcción de Ciudadanía y la Seguridad-CECOISE,
  Escuela de Gestión y Autodesarrollo Indígena,
  Instituto de Estudios Indígenas,
  Centro de Estudios para el Arte y la Cultura-CEUNACH,
  Escuela de Sistemas Alternativos-SIAL;
  `;
};

export const ES = () => {
    return `Profesor o Profesora de Tiempo Completo,
    Profesor o Profesora de Medio Tiempo,
    Profesor o Profesora de Asignatura,
    Profesor o Profesora de Honorarios,
    Cátedras CONACYT,
    Retención / Repatriación,
    Estancia Posdoctoral,
    Otro.Indicar:
  `;
};

export const KA = () => {
    return `
    Físico-Matemáticas y Ciencias de la Tierra,
Biología y Química,
Medicina y Ciencias de la Salud,
Ciencias de la Conducta y la Educación,
Humanidades,
Ciencias Sociales,
Ciencias de Agricultura- Agropecuarias- Forestales y de Ecosistemas,
Ingeniería y Desarrollo Tecnológico,
Interdisciplinaria,

  `;
};

export const D = () => {
    return `
    
    Astronomía,
Física,
Matemáticas,
Óptica,
Geología,
Geofísica,
Geoquímica,
Geografía Física,
Oceanografía,
Limnología,
Hidrología,
Ciencias de la Atmósfera,
Contaminación de agua- Aire y Suelo,
Química,
Bioquímica,
Biofísica,
Biología,
Fisiología,
Biología Celular y Molecular,
Neurociencias,
Genética,
Farmacología,
Síntesis de Productos Naturales,
Ecología,
Evolución y Sistemática de Organismos Terrestres y Acuáticos - Vegetales- Animales- Hongos y Microorganismos,
Ciencias Biomédicas,
Inmunología,
Salud Pública,
Epidemiología,
Antropología Física,
Arqueología,
Estética,
Etnohistoria,
Filología,
Filosofía,
Historia,
Arquitectura y Urbanismo,
Psicología,
Literatura,
Lingüística,
Sociología,
Antropología Social,
Demografía,
Educación,
Comunicación,
Derecho,
Etnología,
Economía,
Administración y Políticas Públicas,
Administración Privada,
Ciencias Políticas,
Relaciones Internacionales,
Acuacultura y Pesquerías,
Ciencias Agronómicas y Forestales,
Medicina Veterinaria y Zootecnia,
Alimentos,
Microbiología,
Biorremediación Ambiental,
Sanidad,
Fisiología Animal y Vegetal,
Ingeniería Industrial,
Ingeniería Química,
Ingeniería Electrónica,
Ingeniería Eléctrica,
Instrumentación,
Informática de Sistemas de cómputo,
Ingeniería en Telecomunicaciones,
Ingeniería Aeronáutica,
Ingeniería de Control,
Ingeniería Robótica,
Ingeniería Mecatrónica,
Ingeniería Nuclear,
Ingeniería Civil,
Ingeniería Ambiental,
Ingeniería Mecánica,
Ingeniería Hidráulica,
Ingeniería Metalúrgica,
Ingeniería  de Materiales ,
Ingeniería  de Polímeros y Corrosión,
Otro
  `;
};